# site settings
title: LiDAR SLAM
subtitle: by Emma Pan and Eamon O'Brien
email: youremailaddress@gmail.com
description: Emma Pan and Eamon O'Brien, CompRobo 2020
baseurl: "/LiDAR-SLAM" # the subpath of your site, e.g. /blog
url: "https://epan547.github.io" # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/epan547/LiDAR-SLAM/tree/main
gitlab_url: 
linkedin_url: 
500px_url:
facebook_url:
googleplus_url: 
instagram_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
